/* SE EXPORTA UNA FUNCION
ESTA FUNCION, NECESITA DE EXPRESS PARA FUNCIONAR
ES POR ESO QUE ESTA RECIBIENDO EL PARAMETRO APP QUE LE PASA
EL ARCHIVO INDEX.JS
ES UNA FUNCION FLECHA PERO PUEDE SER UNA FUNCION TRADICIONAL DE JS */

module.exports = (app) =>{
    app.get('/',(req,res)=>{
        res.send('Hola mundo');
    });
}