const mysql = require('mysql');

/*  ESTE MODULO QUE ESTAMOS EXPORTANDO/CREANDO
NOS RETORNA UNA FUNCION CON LAS CREDENCIALES DE LA CONEXION
A LA BD, ASI PODEMOS USAR LAS ACCIONES BASICAS SIN TENER QUE ESTAR
ESCRIBIENDO ESTAS LINEAS EN CADA ARCHIVO
YA SOLO LA LLAMAMOS Y HACEMOS LAS ACCIONES QUE NECESITEMOS HACER
CREAR-MODIFICAR-BORRAR-ACTUALIZAR-ETC
LAS RUTAS SE ENCARGARAN DE MANEJAR ESTAS FUNCIONES YA QUE SON LAS QUE
RECIBEN LAS PETICIONES DEL PROTOCOLO HTTP */

module.exports = () =>{
    return mysql.createConnection({
        host:'localhost',
        user: 'root',
        password:'root',
        database:'portal_noticias_nodejs'
    });
}